### ISSUE TITLE
Questions to discuss the safety feature

### ISSUE THREAD

**Issue by zanfi2010** [sfrwmaker/TFT_Rework_station#1]
Hello Alexander:

I can't sign up the www.hackster.io, so I leave the messages here.

Your project is great and I'm studying it.

There are some questions to discuss the safety feature. Safety is the first. Some idears from me, please correct me if my understandings are wrong.

1. If the relay K1 is OFF but the Main switch is ON, the power still deliver to GX16.
![0](https://user-images.githubusercontent.com/94744206/142762126-3a561574-27cd-4eef-b2fd-a28ff9e0c995.PNG)

Maybe we can use two relays. relay K1 to used to cut off the power to GX16, and relay K2 be used to automaticslly turn-off the power after the Main switch is off. And it need the second control signal named “HOT_GUN_ENABLE_2” below.
![1](https://user-images.githubusercontent.com/94744206/142762170-ffe10f03-9548-47cb-b8ee-79b70689b332.PNG)

For further, we can connect the triode VT6‘s emitter to GND on Air Gun handle. When the GX16 is removed, the relay K1 will be turn off automatically even if the MCU fails. Then it need nine pins aviation plug and can be got from online shop.
![3](https://user-images.githubusercontent.com/94744206/142763379-760e4acc-e1e0-4be4-94c2-5e4956442451.png)

Maybe it can be simplified:
a. Use one relay with 11 pins(U10);
b. Use Bidirectional Optocoupler(U11);
c. Use zero-cross optoisolators triac driver(U12), and I think that the U11 can be simplified too.
![5](https://user-images.githubusercontent.com/94744206/143031334-cd73d5ac-e853-49b5-911b-22f39d4ce8e0.png)

2. The GX16 can be used another type as below. I think it will be more safety.
![2](https://user-images.githubusercontent.com/94744206/142763156-c45e25d2-adbf-48d8-83e1-54c5a89a65ec.png)

I'm copying you project, welcome to: https://oshwhub.com/zanfi1010/stm32_rework_tft

**Comment by sfrwmaker** [comment]
First of all, you are right! It is not completely safe. When the relay was introduced in the project, it operates on both AC lines, N and L. Then somebody asked to introduce the 'delayed power-off' feature and i thought that two relays are too much. :) So, i managed one line via relay and another via the TRIAC, as you can see. The path you have highlighted goes through 1Mohm resistor R44. I do believe nobody will be hurted through it. And yes, it is nice to replace the socket also. Or you can use another relay with 3 or 4 contacts.
This project was create to inspire people for good ideas first of all. :)

**Comment by zanfi2010** [comment]
I'll try part of my ideas in my duplicate project.
Thanka a lot!
